-- Story Nook Supabase Phase 1 Setup
-- Run this in Supabase Dashboard -> SQL Editor.
-- This creates/updates the backend for accounts, profiles, stories, comments, likes,
-- prompts, rewards, saved stories, points, achievements, reports, feedback, and avatar uploads.

create extension if not exists pgcrypto;
create schema if not exists story_nook_private;
grant usage on schema story_nook_private to anon, authenticated;

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    username text unique not null,
    avatar_url text,
    bio text,
    selected_flair_id bigint,
    display_title text,
    points_total integer not null default 0,
    level integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists bio text;
alter table public.profiles add column if not exists selected_flair_id bigint;
alter table public.profiles add column if not exists display_title text;
alter table public.profiles add column if not exists points_total integer not null default 0;
alter table public.profiles add column if not exists level integer not null default 1;
alter table public.profiles add column if not exists created_at timestamptz not null default now();
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create or replace function story_nook_private.is_nook_admin()
returns boolean language sql stable security definer set search_path = public as $$
    select coalesce(auth.jwt() ->> 'email', '') = 'chdrey@gmail.com'
        or exists (select 1 from public.profiles p where p.id = auth.uid() and p.username = 'PenPaleto');
$$;
grant execute on function story_nook_private.is_nook_admin() to anon, authenticated;

create or replace function public.is_nook_admin()
returns boolean language sql stable set search_path = public as $$
    select story_nook_private.is_nook_admin();
$$;
revoke execute on function public.is_nook_admin() from public, anon, authenticated;

create table if not exists public.flairs (
    id bigint primary key,
    name text not null,
    css_class text not null,
    reward_type text not null default 'flair' check (reward_type in ('flair', 'badge', 'frame', 'title')),
    unlock_points integer,
    description text,
    created_at timestamptz not null default now()
);
alter table public.flairs add column if not exists reward_type text not null default 'flair';
alter table public.flairs add column if not exists unlock_points integer;
insert into public.flairs (id, name, css_class, description) values
    (1, 'The Bard', 'frame-wood', 'Participated in the weekly prompt.'),
    (2, 'Talk of the Nook', 'frame-copper', 'Earned for lively discussion.'),
    (3, 'The Ink Scribble', 'frame-stone', 'Third place in weekly voting.'),
    (4, 'The Cliffhanger', 'frame-iron', 'Second place in weekly voting.'),
    (5, 'The Golden Quill', 'frame-gold', 'First place in weekly voting.'),
    (6, 'The Trilogy Master', 'frame-diamond', 'Top 3 for three weeks in a row.')
on conflict (id) do update set
    name = excluded.name,
    css_class = excluded.css_class,
    description = excluded.description;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'profiles_selected_flair_id_fkey'
          and conrelid = 'public.profiles'::regclass
    ) then
        alter table public.profiles
            add constraint profiles_selected_flair_id_fkey
            foreign key (selected_flair_id) references public.flairs(id) on delete set null;
    end if;
end $$;

create table if not exists public.user_flairs (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    flair_id bigint not null references public.flairs(id) on delete cascade,
    source text default 'manual',
    created_at timestamptz not null default now()
);
create index if not exists user_flairs_user_idx on public.user_flairs(user_id);
create unique index if not exists user_flairs_user_flair_unique_idx on public.user_flairs(user_id, flair_id);

create or replace function public.protect_profile_engagement_fields()
returns trigger language plpgsql security definer set search_path = public as $$
begin
    if current_setting('story_nook.allow_points_update', true) = 'on' then
        return new;
    end if;

    if auth.uid() = old.id and not story_nook_private.is_nook_admin() then
        new.points_total = old.points_total;
        new.level = old.level;

        if new.selected_flair_id is not null
           and new.selected_flair_id is distinct from old.selected_flair_id
           and not exists (
               select 1
               from public.user_flairs uf
               where uf.user_id = old.id
                 and uf.flair_id = new.selected_flair_id
           ) then
            raise exception 'That flair has not been unlocked yet.';
        end if;
    end if;

    return new;
end;
$$;
revoke execute on function public.protect_profile_engagement_fields() from public, anon, authenticated;

create table if not exists public.prompts (
    id bigint generated by default as identity primary key,
    title text,
    body text not null,
    status text not null default 'draft' check (status in ('draft', 'active', 'archived')),
    starts_at timestamptz,
    ends_at timestamptz,
    created_by uuid references public.profiles(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
alter table public.prompts add column if not exists title text;
alter table public.prompts add column if not exists body text not null default '';
alter table public.prompts add column if not exists status text not null default 'draft';
alter table public.prompts add column if not exists starts_at timestamptz;
alter table public.prompts add column if not exists ends_at timestamptz;
alter table public.prompts add column if not exists created_by uuid references public.profiles(id) on delete set null;
alter table public.prompts add column if not exists created_at timestamptz not null default now();
alter table public.prompts add column if not exists updated_at timestamptz not null default now();
create index if not exists prompts_status_starts_idx on public.prompts(status, starts_at desc);

create table if not exists public.stories (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles(id) on delete set null,
    prompt_id bigint references public.prompts(id) on delete set null,
    guest_name text,
    content text not null,
    votes integer not null default 0,
    view_count integer not null default 0,
    deleted_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
alter table public.stories add column if not exists prompt_id bigint references public.prompts(id) on delete set null;
alter table public.stories add column if not exists guest_name text;
alter table public.stories add column if not exists votes integer not null default 0;
alter table public.stories add column if not exists view_count integer not null default 0;
alter table public.stories add column if not exists deleted_at timestamptz;
alter table public.stories add column if not exists created_at timestamptz not null default now();
alter table public.stories add column if not exists updated_at timestamptz not null default now();
create index if not exists stories_user_idx on public.stories(user_id);
create index if not exists stories_prompt_idx on public.stories(prompt_id);
create index if not exists stories_live_created_idx on public.stories(created_at desc) where deleted_at is null;
create index if not exists stories_live_votes_created_idx on public.stories(votes desc, created_at desc) where deleted_at is null;

create table if not exists public.story_likes (
    story_id bigint not null references public.stories(id) on delete cascade,
    user_id uuid not null references public.profiles(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (story_id, user_id)
);
create index if not exists story_likes_user_idx on public.story_likes(user_id);

create or replace function public.sync_story_vote_count()
returns trigger language plpgsql security definer set search_path = public as $$
declare
    v_story_id bigint;
begin
    v_story_id = coalesce(new.story_id, old.story_id);

    update public.stories s
       set votes = (
               select count(*)::integer
               from public.story_likes sl
               where sl.story_id = v_story_id
           ),
           updated_at = now()
     where s.id = v_story_id
       and s.deleted_at is null;

    return coalesce(new, old);
end;
$$;
revoke execute on function public.sync_story_vote_count() from public, anon, authenticated;

create table if not exists public.saved_stories (
    user_id uuid not null references public.profiles(id) on delete cascade,
    story_id bigint not null references public.stories(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (user_id, story_id)
);
create index if not exists saved_stories_story_idx on public.saved_stories(story_id);

create or replace function public.like_story(p_story_id bigint)
returns integer language plpgsql security invoker set search_path = public as $$
declare v_votes integer;
begin
    if auth.uid() is null then
        raise exception 'You must be logged in to like a story.';
    end if;

    if not exists (
        select 1
        from public.stories s
        where s.id = p_story_id
          and s.deleted_at is null
    ) then
        raise exception 'Story is unavailable.';
    end if;

    insert into public.story_likes (story_id, user_id)
    values (p_story_id, auth.uid())
    on conflict do nothing;

    select count(*)::integer
      into v_votes
      from public.story_likes sl
     where sl.story_id = p_story_id;

    return coalesce(v_votes, 0);
end;
$$;
revoke execute on function public.like_story(bigint) from public, anon;
grant execute on function public.like_story(bigint) to authenticated;

create table if not exists public.comments (
    id bigint generated by default as identity primary key,
    story_id bigint not null references public.stories(id) on delete cascade,
    user_id uuid references public.profiles(id) on delete set null,
    guest_name text,
    content text not null,
    deleted_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
alter table public.comments add column if not exists guest_name text;
alter table public.comments add column if not exists deleted_at timestamptz;
alter table public.comments add column if not exists created_at timestamptz not null default now();
alter table public.comments add column if not exists updated_at timestamptz not null default now();
create index if not exists comments_story_idx on public.comments(story_id);
create index if not exists comments_user_idx on public.comments(user_id);

create table if not exists public.point_events (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    event_type text not null check (event_type in ('posted_story', 'received_like', 'received_comment', 'weekly_top_story', 'monthly_top_story', 'manual_adjustment')),
    points integer not null,
    story_id bigint references public.stories(id) on delete set null,
    comment_id bigint references public.comments(id) on delete set null,
    prompt_id bigint references public.prompts(id) on delete set null,
    source_user_id uuid references public.profiles(id) on delete set null,
    note text,
    created_at timestamptz not null default now()
);
create index if not exists point_events_user_created_idx on public.point_events(user_id, created_at desc);
create index if not exists point_events_story_idx on public.point_events(story_id);
create unique index if not exists point_events_unique_post_idx
    on public.point_events(event_type, user_id, story_id)
    where event_type = 'posted_story' and story_id is not null;
create unique index if not exists point_events_unique_like_idx
    on public.point_events(event_type, user_id, story_id, source_user_id)
    where event_type = 'received_like' and story_id is not null and source_user_id is not null;
create unique index if not exists point_events_unique_comment_idx
    on public.point_events(event_type, user_id, comment_id)
    where event_type = 'received_comment' and comment_id is not null;

create or replace function public.record_point_event(
    p_user_id uuid,
    p_event_type text,
    p_points integer,
    p_story_id bigint default null,
    p_comment_id bigint default null,
    p_prompt_id bigint default null,
    p_source_user_id uuid default null,
    p_note text default null
)
returns void language plpgsql security definer set search_path = public as $$
declare
    v_points integer;
    v_new_total integer;
begin
    if p_user_id is null or p_points = 0 then
        return;
    end if;

    insert into public.point_events (
        user_id,
        event_type,
        points,
        story_id,
        comment_id,
        prompt_id,
        source_user_id,
        note
    )
    values (
        p_user_id,
        p_event_type,
        p_points,
        p_story_id,
        p_comment_id,
        p_prompt_id,
        p_source_user_id,
        p_note
    )
    on conflict do nothing
    returning points into v_points;

    if v_points is null then
        return;
    end if;

    perform set_config('story_nook.allow_points_update', 'on', true);

    update public.profiles
       set points_total = greatest(0, points_total + v_points)
     where id = p_user_id
     returning points_total into v_new_total;

    update public.profiles
       set level = greatest(1, floor(sqrt(v_new_total::numeric / 50))::integer + 1)
     where id = p_user_id;

    perform set_config('story_nook.allow_points_update', 'off', true);
end;
$$;
revoke execute on function public.record_point_event(uuid, text, integer, bigint, bigint, bigint, uuid, text) from public, anon, authenticated;

create or replace function public.award_story_post_points()
returns trigger language plpgsql security definer set search_path = public as $$
begin
    if new.user_id is not null then
        perform public.record_point_event(new.user_id, 'posted_story', 10, new.id, null, new.prompt_id, null, null);
    end if;
    return new;
end;
$$;
revoke execute on function public.award_story_post_points() from public, anon, authenticated;

create or replace function public.award_story_like_points()
returns trigger language plpgsql security definer set search_path = public as $$
declare
    v_story_owner uuid;
    v_prompt_id bigint;
begin
    select s.user_id, s.prompt_id
      into v_story_owner, v_prompt_id
      from public.stories s
     where s.id = new.story_id
       and s.deleted_at is null;

    if v_story_owner is not null and v_story_owner <> new.user_id then
        perform public.record_point_event(v_story_owner, 'received_like', 1, new.story_id, null, v_prompt_id, new.user_id, null);
    end if;

    return new;
end;
$$;
revoke execute on function public.award_story_like_points() from public, anon, authenticated;

create or replace function public.award_story_comment_points()
returns trigger language plpgsql security definer set search_path = public as $$
declare
    v_story_owner uuid;
    v_prompt_id bigint;
begin
    select s.user_id, s.prompt_id
      into v_story_owner, v_prompt_id
      from public.stories s
     where s.id = new.story_id
       and s.deleted_at is null;

    if v_story_owner is not null and (new.user_id is null or v_story_owner <> new.user_id) then
        perform public.record_point_event(v_story_owner, 'received_comment', 2, new.story_id, new.id, v_prompt_id, new.user_id, null);
    end if;

    return new;
end;
$$;
revoke execute on function public.award_story_comment_points() from public, anon, authenticated;

create table if not exists public.achievements (
    id bigint generated by default as identity primary key,
    code text unique not null,
    name text not null,
    description text,
    reward_flair_id bigint references public.flairs(id) on delete set null,
    points integer not null default 0,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.user_achievements (
    user_id uuid not null references public.profiles(id) on delete cascade,
    achievement_id bigint not null references public.achievements(id) on delete cascade,
    story_id bigint references public.stories(id) on delete set null,
    prompt_id bigint references public.prompts(id) on delete set null,
    earned_at timestamptz not null default now(),
    primary key (user_id, achievement_id, earned_at)
);
create index if not exists user_achievements_user_idx on public.user_achievements(user_id, earned_at desc);

create table if not exists public.content_reports (
    id bigint generated by default as identity primary key,
    reporter_id uuid references public.profiles(id) on delete set null,
    target_type text not null check (target_type in ('story', 'comment')),
    target_id bigint not null,
    reason text,
    created_at timestamptz not null default now()
);

create table if not exists public.feedback (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles(id) on delete set null,
    email text,
    message text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
    key text primary key,
    value text not null,
    updated_by uuid references public.profiles(id) on delete set null,
    updated_at timestamptz not null default now()
);
alter table public.site_settings add column if not exists value text not null default '';
alter table public.site_settings add column if not exists updated_by uuid references public.profiles(id) on delete set null;
alter table public.site_settings add column if not exists updated_at timestamptz not null default now();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists profiles_protect_engagement_fields on public.profiles;
create trigger profiles_protect_engagement_fields before update on public.profiles
for each row execute function public.protect_profile_engagement_fields();

drop trigger if exists stories_set_updated_at on public.stories;
create trigger stories_set_updated_at before update on public.stories
for each row execute function public.set_updated_at();

drop trigger if exists stories_award_post_points on public.stories;
create trigger stories_award_post_points after insert on public.stories
for each row execute function public.award_story_post_points();

drop trigger if exists story_likes_award_points on public.story_likes;
create trigger story_likes_award_points after insert on public.story_likes
for each row execute function public.award_story_like_points();

drop trigger if exists story_likes_sync_vote_count_insert on public.story_likes;
create trigger story_likes_sync_vote_count_insert after insert on public.story_likes
for each row execute function public.sync_story_vote_count();

drop trigger if exists story_likes_sync_vote_count_delete on public.story_likes;
create trigger story_likes_sync_vote_count_delete after delete on public.story_likes
for each row execute function public.sync_story_vote_count();

drop trigger if exists prompts_set_updated_at on public.prompts;
create trigger prompts_set_updated_at before update on public.prompts
for each row execute function public.set_updated_at();

drop trigger if exists comments_set_updated_at on public.comments;
create trigger comments_set_updated_at before update on public.comments
for each row execute function public.set_updated_at();

drop trigger if exists comments_award_points on public.comments;
create trigger comments_award_points after insert on public.comments
for each row execute function public.award_story_comment_points();

drop trigger if exists site_settings_set_updated_at on public.site_settings;
create trigger site_settings_set_updated_at before update on public.site_settings
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.flairs enable row level security;
alter table public.user_flairs enable row level security;
alter table public.prompts enable row level security;
alter table public.stories enable row level security;
alter table public.story_likes enable row level security;
alter table public.saved_stories enable row level security;
alter table public.comments enable row level security;
alter table public.point_events enable row level security;
alter table public.achievements enable row level security;
alter table public.user_achievements enable row level security;
alter table public.content_reports enable row level security;
alter table public.feedback enable row level security;
alter table public.site_settings enable row level security;

drop policy if exists profiles_read_all on public.profiles;
create policy profiles_read_all on public.profiles for select using (true);
drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own on public.profiles for insert with check (auth.uid() = id);
drop policy if exists profiles_update_own_or_admin on public.profiles;
create policy profiles_update_own_or_admin on public.profiles for update using (auth.uid() = id or story_nook_private.is_nook_admin()) with check (auth.uid() = id or story_nook_private.is_nook_admin());
drop policy if exists profiles_delete_own_or_admin on public.profiles;
create policy profiles_delete_own_or_admin on public.profiles for delete using (auth.uid() = id or story_nook_private.is_nook_admin());

drop policy if exists flairs_read_all on public.flairs;
create policy flairs_read_all on public.flairs for select using (true);
drop policy if exists flairs_admin_write on public.flairs;
create policy flairs_admin_write on public.flairs for all using (story_nook_private.is_nook_admin()) with check (story_nook_private.is_nook_admin());

drop policy if exists user_flairs_read_all on public.user_flairs;
create policy user_flairs_read_all on public.user_flairs for select using (true);
drop policy if exists user_flairs_admin_write on public.user_flairs;
create policy user_flairs_admin_write on public.user_flairs for all using (story_nook_private.is_nook_admin()) with check (story_nook_private.is_nook_admin());

drop policy if exists prompts_read_published on public.prompts;
create policy prompts_read_published on public.prompts for select using (status in ('active', 'archived') or story_nook_private.is_nook_admin());
drop policy if exists prompts_admin_write on public.prompts;
create policy prompts_admin_write on public.prompts for all using (story_nook_private.is_nook_admin()) with check (story_nook_private.is_nook_admin());

drop policy if exists stories_read_live on public.stories;
create policy stories_read_live on public.stories for select using (deleted_at is null or user_id = auth.uid() or story_nook_private.is_nook_admin());
drop policy if exists stories_insert_own_or_guest on public.stories;
create policy stories_insert_own_or_guest on public.stories for insert with check ((auth.uid() is null and user_id is null and guest_name is not null) or (auth.uid() = user_id));
drop policy if exists stories_update_owner_or_admin on public.stories;
create policy stories_update_owner_or_admin on public.stories for update using (user_id = auth.uid() or story_nook_private.is_nook_admin()) with check (user_id = auth.uid() or story_nook_private.is_nook_admin());
drop policy if exists stories_delete_owner_or_admin on public.stories;
create policy stories_delete_owner_or_admin on public.stories for delete using (user_id = auth.uid() or story_nook_private.is_nook_admin());

drop policy if exists story_likes_read_all on public.story_likes;
create policy story_likes_read_all on public.story_likes for select using (true);
drop policy if exists story_likes_insert_own on public.story_likes;
create policy story_likes_insert_own on public.story_likes for insert with check (auth.uid() = user_id);
drop policy if exists story_likes_delete_own on public.story_likes;
create policy story_likes_delete_own on public.story_likes for delete using (auth.uid() = user_id or story_nook_private.is_nook_admin());

drop policy if exists saved_stories_read_own on public.saved_stories;
create policy saved_stories_read_own on public.saved_stories for select using (auth.uid() = user_id or story_nook_private.is_nook_admin());
drop policy if exists saved_stories_insert_own on public.saved_stories;
create policy saved_stories_insert_own on public.saved_stories for insert with check (auth.uid() = user_id);
drop policy if exists saved_stories_delete_own on public.saved_stories;
create policy saved_stories_delete_own on public.saved_stories for delete using (auth.uid() = user_id or story_nook_private.is_nook_admin());

drop policy if exists comments_read_live on public.comments;
create policy comments_read_live on public.comments for select using (deleted_at is null or user_id = auth.uid() or story_nook_private.is_nook_admin());
drop policy if exists comments_insert_own_or_guest on public.comments;
create policy comments_insert_own_or_guest on public.comments for insert with check ((auth.uid() is null and user_id is null and guest_name is not null) or (auth.uid() = user_id));
drop policy if exists comments_update_owner_or_admin on public.comments;
create policy comments_update_owner_or_admin on public.comments for update using (user_id = auth.uid() or story_nook_private.is_nook_admin()) with check (user_id = auth.uid() or story_nook_private.is_nook_admin());
drop policy if exists comments_delete_owner_or_admin on public.comments;
create policy comments_delete_owner_or_admin on public.comments for delete using (user_id = auth.uid() or story_nook_private.is_nook_admin());

drop policy if exists point_events_read_own_or_admin on public.point_events;
create policy point_events_read_own_or_admin on public.point_events for select using (auth.uid() = user_id or story_nook_private.is_nook_admin());
drop policy if exists point_events_admin_write on public.point_events;
create policy point_events_admin_write on public.point_events for all using (story_nook_private.is_nook_admin()) with check (story_nook_private.is_nook_admin());

drop policy if exists achievements_read_active on public.achievements;
create policy achievements_read_active on public.achievements for select using (is_active or story_nook_private.is_nook_admin());
drop policy if exists achievements_admin_write on public.achievements;
create policy achievements_admin_write on public.achievements for all using (story_nook_private.is_nook_admin()) with check (story_nook_private.is_nook_admin());

drop policy if exists user_achievements_read_all on public.user_achievements;
create policy user_achievements_read_all on public.user_achievements for select using (true);
drop policy if exists user_achievements_admin_write on public.user_achievements;
create policy user_achievements_admin_write on public.user_achievements for all using (story_nook_private.is_nook_admin()) with check (story_nook_private.is_nook_admin());

drop policy if exists reports_insert_anyone on public.content_reports;
create policy reports_insert_anyone on public.content_reports for insert with check (reporter_id is null or reporter_id = auth.uid());
drop policy if exists reports_admin_read on public.content_reports;
create policy reports_admin_read on public.content_reports for select using (story_nook_private.is_nook_admin());

drop policy if exists feedback_insert_anyone on public.feedback;
create policy feedback_insert_anyone on public.feedback for insert with check (user_id is null or user_id = auth.uid());
drop policy if exists feedback_admin_read on public.feedback;
create policy feedback_admin_read on public.feedback for select using (story_nook_private.is_nook_admin());

drop policy if exists site_settings_read_all on public.site_settings;
create policy site_settings_read_all on public.site_settings for select using (true);
drop policy if exists site_settings_admin_write on public.site_settings;
create policy site_settings_admin_write on public.site_settings for all using (story_nook_private.is_nook_admin()) with check (story_nook_private.is_nook_admin());

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do update set public = true;

drop policy if exists avatars_read_public on storage.objects;
drop policy if exists avatars_upload_own on storage.objects;
create policy avatars_upload_own on storage.objects for insert with check (bucket_id = 'avatars' and auth.uid()::text = (storage.foldername(name))[1]);
drop policy if exists avatars_update_own on storage.objects;
create policy avatars_update_own on storage.objects for update using (bucket_id = 'avatars' and auth.uid()::text = (storage.foldername(name))[1]) with check (bucket_id = 'avatars' and auth.uid()::text = (storage.foldername(name))[1]);
drop policy if exists avatars_delete_own on storage.objects;
create policy avatars_delete_own on storage.objects for delete using (bucket_id = 'avatars' and auth.uid()::text = (storage.foldername(name))[1]);
